### ISSUE TITLE
Add CCI macro

### ISSUE THREAD

**Issue by thomas-rasmussen** [thomas-rasmussen/sas_macros#35]
Consider making a polished macro that calculates the Charlson Comorbidity Index for each person in an input dataset, based on diagnosis data given in another dataset. Make macro based on newest local CCI macro. Maybe the one used in the Brain disorder project? Start by making an initial experimental version that implements the CCI "as it is usually done at the department". At some point, go through the litterature to figure out exactly what version of the CCI that is (if any) and find and include references.

**Comment by divaDseidnA** [comment]
Wow, this idea looks great! We use an older one currently, and I would
gladly contribute. Would you use normal sas tables or an excel to add CCI
disease definitions?

**Comment by thomas-rasmussen** [comment]
Hi David. Thank you for offering to help, but I don' think it will be necesary for the first implementation I'm planning, since IIRC my local version is already more or less working as I want it to.  Or at the very least, I know how I want it to work and how to implement it already.

The way it works currently (I think) is that all the diagnosis codes are stored in macro variables inside the macro, and there is also some options for providing the code definitions yourself through macro parameters I think. I would also like to point out that this is an Excel-free zone;)

Are you using the old comorbidityxxxx macros? Can I convince you to test my version once it's done? I have had no feedback on it so far I think, but I (obviously) think my version is quite the upgrade, eg it is way more efficient than the older versions.
